-- Table of directors
CREATE TABLE directors (
    id SERIAL PRIMARY KEY ,
    user_id INT REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    rol_id INT REFERENCES rols(id) ON DELETE SET NULL ON UPDATE CASCADE
);